//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsEntities : DbContext
    {
        public CarsEntities()
            : base("name=CarsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyCar> MyCars { get; set; }

        internal void AddToCarSet(MyCar carToCreate)
        {
            MyCars.Add(carToCreate);
        }

        internal void ChangeAvailability(int Id,string renterId)
        {
            if (Id != -1)
            {
                MyCars.Find(Id).Renter = String.Copy(renterId);
                MyCars.Find(Id).Available = false;
            }
        }
    }
}
