//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCar
    {
        public int Id { get; set; }
        public string LicencePlate { get; set; }
        public string Brand { get; set; }
        public string Name { get; set; }
        public bool Available { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }

        public override string ToString()
        {
            return LicencePlate+ " "+Brand+" "+Name;
        }
    }
}
